development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://mzbxzbeevypyvx:f180f81edc6de052b86c2881d6e6f562251b6c0e39cc581a1f6e48638141a69c@ec2-54-225-192-243.compute-1.amazonaws.com:5432/d5b40v9fvj0fh3
  channel_prefix: nameofapp_production
